Create Database FlightBooking;
Use FlightBooking;

CREATE TABLE HANHKHACH (
    MAHK NVARCHAR(50) PRIMARY KEY,
    HOTEN NVARCHAR(100),
    DIACHI NVARCHAR(200),
    DIENTHOAI NVARCHAR(20)
);

CREATE TABLE MAYBAY (
    MAMB NVARCHAR(50) PRIMARY KEY,
    HANGMB NVARCHAR(100),
    SOCHO INT
);

CREATE TABLE CHUYENBAY (
    MACH NVARCHAR(50) PRIMARY KEY,
    CHUYEN NVARCHAR(100),
    DDI NVARCHAR(50),
    DDEN NVARCHAR(50),
    NGAY DATE,
    GBAY TIME,
    GDEN TIME,
    THUONG INT,
    VIP INT,
    MAMB NVARCHAR(50),
    FOREIGN KEY (MAMB) REFERENCES MAYBAY(MAMB)
);

CREATE TABLE CT_CB (
    MACH NVARCHAR(50),
    MAHK NVARCHAR(50),
    SOGHE NVARCHAR(10),
    LOAIGHE BIT,
    PRIMARY KEY (MACH, MAHK),
    FOREIGN KEY (MACH) REFERENCES CHUYENBAY(MACH),
    FOREIGN KEY (MAHK) REFERENCES HANHKHACH(MAHK)
);

-- Thêm dữ liệu mẫu
INSERT INTO HANHKHACH VALUES ('HK001', 'Alice', 'Hanoi', '0123456789');
INSERT INTO HANHKHACH VALUES ('HK002', 'Bob', 'HCMC', '0987654321');
INSERT INTO MAYBAY VALUES ('MB001', 'Boeing', 100);
INSERT INTO CHUYENBAY VALUES ('CB0001', 'SG_HN', 'HCMC', 'Hanoi', '2023-11-01', '08:00', '10:00', 80, 20, 'MB001');
INSERT INTO CT_CB VALUES ('CB0001', 'HK001', '26A', 0);
INSERT INTO CT_CB VALUES ('CB0001', 'HK002', '27C', 1);